SELECT USER
FROM DUAL;
--==>> SCOTT


-- 1. 인원 수 조회 쿼리문
SELECT COUNT(*) AS COUNT
FROM TBL_SCORE;
--> 한 줄 구성
SELECT COUNT(*) AS COUNT FROM TBL_SCORE
;

-- 2. 성적 입력 쿼리문
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT)
VALUES(10, '채다선', 90, 90, 90);
--> 한 줄 구성
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, '채다선', 90, 90, 90)
;

-- 3. 성적 전체 출력 쿼리문
SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) TOT, (KOR+ENG+MAT)/3 AS AVG
     , RANK() OVER(ORDER BY (KOR+ENG+MAT) DESC) AS RANK
FROM TBL_SCORE;
--> 한 줄 구성
SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) TOT, (KOR+ENG+MAT)/3 AS AVG, RANK() OVER(ORDER BY (KOR+ENG+MAT) DESC) AS RANK FROM TBL_SCORE
;

-- 4. 이름 검색 출력 쿼리문
SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) TOT, (KOR+ENG+MAT)/3 AS AVG
     , RANK() OVER(ORDER BY (KOR+ENG+MAT) DESC) AS RANK
FROM TBL_SCORE
WHERE NAME = '채다선';
--> 한 줄 구성
SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) TOT, (KOR+ENG+MAT)/3 AS AVG, RANK() OVER(ORDER BY (KOR+ENG+MAT) DESC) AS RANK FROM TBL_SCORE WHERE NAME = '채다선'
;

-- 5. 성적 수정 쿼리문
UPDATE TBL_SCORE
SET NAME='채다선', KOR=90, ENG=90, MAT=90
WHERE SID = 1;
--> 한 줄 구성
UPDATE TBL_SCORE SET NAME='채다선', KOR=90, ENG=90, MAT=90 WHERE SID = 1
;

-- 6. 성적 삭제 쿼리문
DELETE
FROM TBL_SCORE
WHERE SID=18;
--> 한 줄 구성
DELETE FROM TBL_SCORE WHERE SID=1
;

commit;



